name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      - name: Build executable
        run: |
          pyinstaller --onefile --windowed --icon=icon.ico main.py
      - name: Upload executable
        uses: actions/upload-artifact@v2
        with:
          name: executable
          path: dist/main